import React, { useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Search, Users, Newspaper, Cake, Trophy, UserPlus, Shield, Plus, Pencil, RotateCcw, UserRound, CalendarDays, Building2, LogOut } from "lucide-react";
import "./styles.css";

const MANAGER_PASSWORD = "change-this-password";
const STORAGE_KEY = "stokes-staff-hub-v1";
const starterEmployees = [
  { id: "1", fullName: "Amelia Carter", role: "Production Operative", department: "Factory", startDate: "2024-03-12", useDefaultIcon: true, photoUrl: "", status: "active" },
  { id: "2", fullName: "Tom Richardson", role: "Warehouse Supervisor", department: "Warehouse", startDate: "2021-09-06", useDefaultIcon: true, photoUrl: "", status: "active" },
  { id: "3", fullName: "Sarah Collins", role: "Technical Assistant", department: "Technical", startDate: "2023-01-18", useDefaultIcon: true, photoUrl: "", status: "active" }
];
function loadEmployees(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||starterEmployees}catch{return starterEmployees}}
function saveEmployees(employees){localStorage.setItem(STORAGE_KEY, JSON.stringify(employees))}
function formatDate(value){if(!value)return"";return new Date(value+"T00:00:00").toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}
function isNewStarter(startDate){if(!startDate)return false;const started=new Date(startDate+"T00:00:00");const days=(new Date()-started)/(1000*60*60*24);return days>=0&&days<=90}
function Avatar({employee,large=false}){const className=large?"avatar avatarLarge":"avatar";if(employee.photoUrl&&!employee.useDefaultIcon)return <img className={className} src={employee.photoUrl} alt={employee.fullName}/>;return <div className={`${className} avatarDefault`}><UserRound size={large?76:42}/></div>}
function Home({setPage,employees}){const active=employees.filter(e=>e.status==="active");const newStarters=active.filter(e=>isNewStarter(e.startDate)).length;return <section className="home"><div className="hero"><p className="eyebrow">Stokes Sauces</p><h1>Good morning 👋</h1><p>Welcome to the Stokes Staff Hub.</p></div><div className="todayCard"><p className="eyebrow">Today at Stokes</p><div className="todayGrid"><div><strong>{active.length}</strong><span>Active staff</span></div><div><strong>{newStarters}</strong><span>New starters</span></div><div><strong>0</strong><span>Announcements</span></div></div></div><div className="homeGrid"><button onClick={()=>setPage("directory")}><Users/><span>Employee Directory</span></button><button><Newspaper/><span>Company News</span></button><button><Cake/><span>Birthdays</span></button><button><Trophy/><span>Work Anniversaries</span></button><button><UserPlus/><span>New Starters</span></button></div></section>}
function EmployeeCard({employee,onClick}){return <button className="employeeCard" onClick={()=>onClick(employee)}><Avatar employee={employee}/><div><div className="rowTitle"><h3>{employee.fullName}</h3>{isNewStarter(employee.startDate)&&<span>New</span>}</div><p>{employee.role}</p><small><CalendarDays size={14}/> Started {formatDate(employee.startDate)}</small></div></button>}
function Directory({employees}){const[query,setQuery]=useState("");const[department,setDepartment]=useState("All");const[selected,setSelected]=useState(null);const active=employees.filter(e=>e.status==="active");const departments=["All",...new Set(active.map(e=>e.department).filter(Boolean))];const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return active.filter(e=>department==="All"||e.department===department).filter(e=>!q||`${e.fullName} ${e.role} ${e.department}`.toLowerCase().includes(q)).sort((a,b)=>a.fullName.localeCompare(b.fullName))},[employees,query,department]);return <><section className="pageHeader"><p className="eyebrow">Directory</p><h2>Find your team.</h2></section><label className="search"><Search size={18}/><input placeholder="Search by name, role or department..." value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="chips">{departments.map(d=><button key={d} onClick={()=>setDepartment(d)} className={department===d?"active":""}>{d}</button>)}</div><section className="directory">{filtered.map(employee=><EmployeeCard key={employee.id} employee={employee} onClick={setSelected}/>)}</section>{selected&&<div className="modalBg" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><Avatar employee={selected} large/><h2>{selected.fullName}</h2><p>{selected.role}</p><div><Building2 size={16}/> {selected.department}</div><div><CalendarDays size={16}/> Started {formatDate(selected.startDate)}</div><button className="primary" onClick={()=>setSelected(null)}>Close</button></div></div>}</>}
function ManagerLogin({onLogin}){const[password,setPassword]=useState("");const[error,setError]=useState("");function submit(e){e.preventDefault();if(password===MANAGER_PASSWORD)onLogin();else setError("Incorrect password. Demo password: change-this-password")}return <section className="login"><Shield size={42}/><h2>Manager Portal</h2><p>Manage employee records, photos and status.</p><form onSubmit={submit}><input type="password" placeholder="Manager password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary">Log in</button></form>{error&&<small className="error">{error}</small>}</section>}
function EmployeeForm({employee,onSave,onCancel}){const[form,setForm]=useState(employee||{fullName:"",role:"",department:"",startDate:"",useDefaultIcon:true,photoUrl:"",status:"active"});function update(key,value){setForm(prev=>({...prev,[key]:value}))}function handlePhoto(file){if(!file)return;const reader=new FileReader();reader.onload=()=>setForm(prev=>({...prev,photoUrl:reader.result,useDefaultIcon:false}));reader.readAsDataURL(file)}function submit(e){e.preventDefault();onSave({...form,id:form.id||crypto.randomUUID()})}return <form className="form" onSubmit={submit}><h3>{employee?"Edit employee":"Add employee"}</h3><input required placeholder="Full name" value={form.fullName} onChange={e=>update("fullName",e.target.value)}/><input required placeholder="Role" value={form.role} onChange={e=>update("role",e.target.value)}/><input required placeholder="Department" value={form.department} onChange={e=>update("department",e.target.value)}/><input required type="date" value={form.startDate} onChange={e=>update("startDate",e.target.value)}/><label className="checkbox"><input type="checkbox" checked={form.useDefaultIcon} onChange={e=>update("useDefaultIcon",e.target.checked)}/> Use default silhouette instead of photo</label>{!form.useDefaultIcon&&<input type="file" accept="image/*" onChange={e=>handlePhoto(e.target.files?.[0])}/>}<div className="actions"><button className="primary">Save</button><button type="button" className="secondary" onClick={onCancel}>Cancel</button></div></form>}
function Manager({employees,setEmployees,logout}){const[showForm,setShowForm]=useState(false);const[editing,setEditing]=useState(null);const[view,setView]=useState("active");const shown=employees.filter(e=>view==="active"?e.status==="active":e.status==="left");function commit(next){setEmployees(next);saveEmployees(next)}function saveEmployee(employee){const exists=employees.some(e=>e.id===employee.id);const next=exists?employees.map(e=>e.id===employee.id?employee:e):[employee,...employees];commit(next);setShowForm(false);setEditing(null)}function markLeft(employee){commit(employees.map(e=>e.id===employee.id?{...e,status:"left"}:e))}function restore(employee){commit(employees.map(e=>e.id===employee.id?{...e,status:"active"}:e))}return <section className="manager"><div className="managerTop"><div><p className="eyebrow">Manager Portal</p><h2>Employee records</h2></div><button className="secondary" onClick={logout}><LogOut size={16}/> Log out</button></div><div className="managerActions"><button className="primary" onClick={()=>setShowForm(true)}><Plus size={16}/> Add employee</button><button className={view==="active"?"tab active":"tab"} onClick={()=>setView("active")}>Active</button><button className={view==="left"?"tab active":"tab"} onClick={()=>setView("left")}>Former employees</button></div>{(showForm||editing)&&<EmployeeForm employee={editing} onSave={saveEmployee} onCancel={()=>{setShowForm(false);setEditing(null)}}/>}<div className="adminList">{shown.map(employee=><div className="adminRow" key={employee.id}><Avatar employee={employee}/><div><strong>{employee.fullName}</strong><p>{employee.role} · {employee.department}</p><small>{employee.status==="active"?`Started ${formatDate(employee.startDate)}`:"Marked as left"}</small></div><div className="rowActions"><button className="secondary" onClick={()=>setEditing(employee)}><Pencil size={15}/> Edit</button>{employee.status==="active"?<button className="secondary" onClick={()=>markLeft(employee)}>Mark as left</button>:<button className="secondary" onClick={()=>restore(employee)}><RotateCcw size={15}/> Restore</button>}</div></div>)}</div></section>}
function App(){const[page,setPage]=useState("home");const[employees,setEmployees]=useState(loadEmployees);const[managerAuthed,setManagerAuthed]=useState(false);return <main><nav><button className="brand" onClick={()=>setPage("home")}>STOKES <span>Staff Hub</span></button><div><button className={page==="home"?"navActive":""} onClick={()=>setPage("home")}>Home</button><button className={page==="directory"?"navActive":""} onClick={()=>setPage("directory")}>Directory</button><button className={page==="manager"?"navActive":""} onClick={()=>setPage("manager")}>Manager</button></div></nav>{page==="home"&&<Home setPage={setPage} employees={employees}/>} {page==="directory"&&<Directory employees={employees}/>} {page==="manager"&&(managerAuthed?<Manager employees={employees} setEmployees={setEmployees} logout={()=>setManagerAuthed(false)}/>:<ManagerLogin onLogin={()=>setManagerAuthed(true)}/>)}</main>}
createRoot(document.getElementById("root")).render(<App/>);
